### Create student
POST localhost:8081/student
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "level": "5",
  "age": 14,
  "gender": "male"
}

### student list
GET localhost:8081/student/all

### Get byId
GET localhost:8081/student/1

### update
PUT localhost:8081/student/update/1
Content-Type: application/json

{
  "name": "test",
  "surname": "tests"
}


### delete
DELETE localhost:8081/student/delete/1


### between
GET localhost:8081/student/between/2024-01-15T12:21:44.643618/2024-01-15T14:06:35.090105


### given date
GET localhost:8081/student/givenDate/2024-01-15T12:21:44.643618

### each field student
POST localhost:8081/student/eachField/
Content-Type: application/json

{
  "name": "VAli",
  "surname": "Aliyev",
  "level": "2",
  "age": 12,
  "gender": "male"
}

### page
GET localhost:8081/student/pagination?page=1&size=10

### paginationsByLevel sorted by id
GET localhost:8081/student/level/2

### paginationsByLevel sorted by id
GET localhost:8081/student/gender/male



